# 1
# price_tier(0)
# 2
submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

app_rating_config_path("./fastlane/metadata/app_store_rating_config.json")

ipa("./fastlane/builds/Calculator2 Assigment.ipa")

submit_for_review(false)

automatic_release(false)
